name: Binary Builds

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod  # Use version from go.mod
          check-latest: true

      - name: Set up Node.js (for minifying CSS and JS)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install minifiers
        run: |
          npm install -g clean-css-cli uglify-js

      - name: Minify all CSS and JS
        run: |
          find internal/resources/static/css -name '*.css' -type f -print -exec cleancss -o {} {} \;
          find internal/resources/static/js -name '*.js' -type f -print -exec uglifyjs {} -o {} \;

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=now::$(date +'%Y%m%d%H%M%S')"

      - name: Create Build Directory
        run: mkdir -p build

      - name: Build for Linux (amd64)
        run: GOOS=linux GOARCH=amd64 go build -ldflags "-X 'wiki-go/internal/version.Version=${{ steps.timestamp.outputs.now }}'" -o build/wiki-go-linux-amd64 .

      - name: Upload Binary to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/wiki-go-linux-amd64
          tag: ${{ steps.timestamp.outputs.now }}
          overwrite: true
          file_glob: false
          release_name: "Release ${{ steps.timestamp.outputs.now }}"
